#TODO ADD IMAGE TO DATE 
FROM nvcr.io/nvidia/tritonserver:NEED_VERSION
RUN pip install transformers==4.34.0 protobuf==3.20.3 sentencepiece==0.1.99 accelerate==0.23.0 einops==0.6.1
RUN pip install --upgrade transformers torch
RUN pip install --upgrade accelerate